### ISSUE TITLE
segfault in a basic assertion while running tests (Rust, Mac M1 Max)

### ISSUE THREAD

**Issue by kurtbuilds** [bluewhalesystems/sold#24]
This very basic test project segfaults when running the tests:

https://github.com/kurtbuilds/sold-segfault

Repro steps:

1. Clone the repo
2. Run `cargo test` or `just test`

Note that it segfaults. If you comment out the `assert_eq` line, it runs successfully.

Mac M1 Max (Late 2021) on stable rust. LMK if there are other system details you need or other info I can share.

```
$ uname -a
Darwin kurts-MBP 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

$ rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)

Mac OS Ventura 13.2.1 (22D68)
```

**Comment by kurtbuilds** [comment]
Thank you!

**Comment by rui314** [comment]
Yup. Thanks for reporting the issue. Feel free to file more bugs if you have any.
