### ISSUE TITLE
Linked executable crashes while catching an exception in C++ on Arm64

### ISSUE THREAD

**Issue by tapthaker** [bluewhalesystems/sold#25]
I have a test like this, but it fails to catch the exception when linked with sold
```lang=objc
- (void) testInvalidPin {

  try {
    // do stuff that throws at std::invalid_argument
  } catch (const std::invalid_argument& e) {
      NSLog(@"Caught exception");
    }
}

```

Here is a reproducer: https://github.com/tapthaker/sold-repro-arm64-std-invalid-parameter

**Comment by rui314** [comment]
Confirmed that it indeed failed. Looking...
