### ISSUE TITLE
Cannot build sold on MacOS

### ISSUE THREAD

**Issue by mildm8nnered** [bluewhalesystems/sold#26]
Following the build instructions at https://github.com/rui314/mold#how-to-build:

```
git clone git@github.com:bluewhalesystems/sold.git
mkdir sold/build
cd sold/build
git checkout v1.10.1
../install-build-deps.sh
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++
cmake --build . -j $(nproc)
sudo cmake --install .
```

Fails at various points:

```
%  git checkout v1.10.1         
error: pathspec 'v1.10.1' did not match any file(s) known to git
```

```
% ../install-build-deps.sh 
../install-build-deps.sh: line 3: /etc/os-release: No such file or directory
```

```
% sw_vers
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217
```

Xcode Version 14.2 (14C18)

**Comment by rui314** [comment]
Please skip `git checkout v1.10.1` since we don't have that tag in this repo.

**Comment by rui314** [comment]
I'll keep tagging versions in this repo since 2.0 which will be released soon.

**Comment by deuszx** [comment]
This still doesn't work. Fails at
```
% ../install-build-deps.sh 
../install-build-deps.sh: line 3: /etc/os-release: No such file or directory
```

**Comment by rui314** [comment]
You don't need to run `install-build-deps.sh` on macOS. Please skip that step and run cmake.

**Comment by mildm8nnered** [comment]
So made more progress but the remaining instructions still won't work out of the box, because in

`cmake --build . -j $(nproc)`

there is no `nproc` command on macOS - I just subbed in the actual number of cores on my machine

**Comment by deuszx** [comment]
And I still can’t check whether sold is used as there’s no readelf on MacOS
and, when using greadelf (MacOS substitute) the binary is not valid ELF
header.

**Comment by deuszx** [comment]
My `~/.cargo/config.toml` looks like this:
```toml
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.mold"]
```
and I still can't see any perf improvements - the build times are exactly the same.

**Comment by deuszx** [comment]
Thanks @rui314 for the suggestion. Unfortunately, I _am_ getting the expected value:
```
otool -l target/release/aleph-node | grep tool
   ntools 1
     tool 54321
```

**Comment by rui314** [comment]
And how many cores does your machine have?

Not that mold/sold can't make the initial build noticeably faster because in the initial build, compiler dominates build time. mold/sold aims to improve build speed for incremental builds where you edit only one or a free file and rebuild your binary.

**Comment by deuszx** [comment]
I'm running it on M2 Pro with 8 high per cores and 4 efficiency ones.

**Comment by rui314** [comment]
And you built your project, edited a source file and then rebuilt with/without sold?

**Comment by jpkeyrock** [comment]
I'm having the same problem here. I did a complete clean/recompile and it looks like there is no improvement (btw having the same machine) despite the reported tool number from `otool` is changing. I'm unfortunately unable to share the souces :(

**Comment by rui314** [comment]
Clean build doesn't benefit a lot from the faster linker because the compiler dominates. mold/sold is intended to speed up incremental builds, i.e. editing a single or a few source file and rebuilding.

**Comment by jpkeyrock** [comment]
I absolutely understand that and went into it with that mindset. For that reason I've examined the build times using `cargo build --timings` And compared just the last step of the build process - the creation of library. For us that's currently 16 seconds (total build time 60 seconds) and it hasn't changed a bit.

**Comment by merlindru** [comment]
Maybe we could add this to the README:

---

## Install

```sh
git clone git@github.com:bluewhalesystems/sold.git
mkdir sold/build
cd ./sold/build
# if you don't have cmake, please run:
# brew install cmake
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ ..
cmake --build . -j $(sysctl -n hw.ncpu)
sudo cmake --build . --target install
```

**Note:** the command to use sold is, by default, `mold`

&nbsp;

## Rust

To use sold with Rust, create `.cargo/config.toml` at the root of your project with the following:

```toml
[target.<platform>]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/path/to/mold"]
```

Change `/path/to/mold` to the absolute path of the `mold` executable (usually `/usr/local/bin/mold`)

Then find out what your platform is:

```sh
rustc -vV | sed -n 's|host: ||p'
```

...and replace the **`<platform>`** in your config.toml with it.

&nbsp;

## Checking whether `mold` was used to link a binary

To find out whether `mold` was used to link your binary, run

```sh
otool -l <your-binary> | grep tool
```

When mold was used, the output should contain **`tool 54321`**
