### ISSUE TITLE
Mold fails to link for Test targets on macOS

### ISSUE THREAD

**Issue by tapthaker** [bluewhalesystems/sold#3]
There is StackOverflow while parsing the XCTest.framework. You should be able to reproduce this using the following script:

```bash
printf 'func blah() {}' > /tmp/hello.swift

xcrun swiftc -c /tmp/hello.swift -o /tmp/hello.o
XCODE_DEVELOPER_DIR=$(xcode-select -p)

"/Users/tapanth/Uber/sold/build-debug/ld64" -demangle -dynamic -arch arm64 \
-syslibroot $XCODE_DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -o /tmp/hello.dylib \
-framework XCTest -framework Foundation \
-lobjc -lSystem \
-F$XCODE_DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks \
/tmp/hello.o
```

I am attaching the crash after turning on Address Sanitizer

[mold_XCTest_failure.txt](https://github.com/bluewhalesystems/sold/files/10453517/mold_XCTest_failure.txt)

**Comment by rui314** [comment]
Can you try again with the above commit?

**Comment by tapthaker** [comment]
I can confirm that the above commit fixes the issue
