### ISSUE TITLE
32 bit arm Mach-O support

### ISSUE THREAD

**Issue by OldWorldOrdr** [bluewhalesystems/sold#30]
Would be nice if this supported armv6/armv7, it would completely eliminate the need for apple's linker when building for those platforms, especially useful on linux where an outdated port of apple's linker is required.

**Comment by rui314** [comment]
It looks like iOS 10 released in 2016  was the last version of the operating system to allow users to run 32-bit apps. So 32 but apps are already very old. Besides that, it's hard to get a hardware as a development platform and maintain it. Therefore it's unlikely to support it. If you fund the project, we might be able to work on it, though.

**Comment by OldWorldOrdr** [comment]
that sucks, i dont have enough money to fund right now but might in the future, how much would you need?

**Comment by OldWorldOrdr** [comment]
also getting hardware to develop on is easy, just buy a cheap iphone 3gs on ebay for like $20, jailbreak, install mterminal from cydia, and you can run cli apps that you transfer over with ssh

**Comment by OldWorldOrdr** [comment]
or if you want something faster, a 4s downgraded to 6.1.3

**Comment by rui314** [comment]
Since the sold linker is commercial software that has paying customers, we need to focus on the features that the paying customers want us to work on. Sorry. _If_ a paying customer would want the ARM32 support, we'd request tens of thousands of dollars.
