### ISSUE TITLE
__eh_frame: unknown LSDA encoding: 0xff

### ISSUE THREAD

**Issue by inflation** [bluewhalesystems/sold#31]
Failed to build hello world rust project.

On last week's version, it failed with `unknown DWARF form for DW_AT_name: 0x8`

**Comment by rui314** [comment]
It should be fixed by the above commit.

**Comment by inflation** [comment]
@rui314 Well, it's still happening:

```
  = note: mold: fatal: /private/tmp/moldtest/target/debug/deps/moldtest-787c3d2ed7e31b50.399hazzrfze7wvgc.rcgu.o: __eh_frame: unknown LSDA encoding: 0xff
```

**Comment by tapthaker** [comment]
+1 ;  I am running into the same issue
