### ISSUE TITLE
Relationship to mold 2.0 regarding Mac support

### ISSUE THREAD

**Issue by xrl** [bluewhalesystems/sold#35]
I saw [the mold 2.0 re-licensing release notes](https://github.com/rui314/mold/releases/tag/v2.0.0) but they did not mention OS X/Darwin/Mac versions. Are you going to backport Mac support to mold or is this commercial offering staying around?

**Comment by rui314** [comment]
Currently I do not have a plan to make a change to the licensing scheme of the sold linker. That being said, Apple is releasing their version of faster linker with the next version of Xcode as announced in the last WWDC. To be honest, that will demote the value of sold as a third-party product. So I guess I need to make a change to our business plan. I haven't decided anything yet.

**Comment by Uzaaft** [comment]
> Currently I do not have a plan to make a change to the licensing scheme of the sold linker. That being said, Apple is releasing their version of faster linker with the next version of Xcode as announced in the last WWDC. To be honest, that will demote the value of sold as a third-party product. So I guess I need to make a change to our business plan. I haven't decided anything yet.

Do you have a source for this? I didnt find any in their docs

**Comment by Alcaro** [comment]
https://developer.apple.com/videos/play/wwdc2022/110362/
Or if you prefer text, https://www.wwdcnotes.com/notes/wwdc22/110362/
> Recent [ld64](https://github.com/apple-opensource/ld64) improvements
> 2x faster in Xcode 14 thanks to better utilization of machine cores

**Comment by seeekr** [comment]
This is the best source we currently have, I think: https://twitter.com/davidecci/status/1665835119331135488

<img width="589" alt="CleanShot 2023-07-28 at 21 14 31@2x" src="https://github.com/bluewhalesystems/sold/assets/302886/cc5777e0-8ff0-490e-9eef-76fc50f46e64">

**Comment by rui314** [comment]
@Alcaro That's the last year's WWDC announcement, and that's for the current slower version of Apple's ld. @seeekr's announcement is about the new one which is announced this year.

**Comment by MarcusJohnson91** [comment]
The new one is called "ld-prime".
