### ISSUE TITLE
README still says mold is AGPLed

### ISSUE THREAD

**Issue by ssokolow** [bluewhalesystems/sold#40]
The sold README is missing an update to "Unlike the mold linker whose license is AGPL" to sync it with the results of commit [a066fe25c6f9ccab11cd07345241492af70d6583](https://github.com/rui314/mold/commit/a066fe25c6f9ccab11cd07345241492af70d6583) on the mold repo.

**Comment by yerke** [comment]
Addressed in https://github.com/bluewhalesystems/sold/commit/67eb15296cfc3b2b6be3835cb0bb65be7dda32e2
