### ISSUE TITLE
Is the project cool with being included in mac homebrew?

### ISSUE THREAD

**Issue by xrl** [bluewhalesystems/sold#57]
I have successfully installed sold and used it with my rust projects. But managing the install with a git checkout and make/make install is a far cry from the simplicity of `brew install sold`. I would like to take a stab at contributing the formula, is the project OK with that?

**Comment by rui314** [comment]
I can't stop you from doing it if you really want to do since it's the MIT license, but I wouldn't recommend because this project is no longer active.

**Comment by rjzak** [comment]
If this project is no longer active, what does that mean for macOS/iOS support and Mold? Could this functionality be brought back to Mold?

**Comment by xrl** [comment]
I'd like to learn more about Apple's faster linker. But if this project is mothballed I'll just close this ticket and forget about it. Thanks!
