### ISSUE TITLE
mold: fatal: unknown command line option: -executable_path

### ISSUE THREAD

**Issue by photex** [bluewhalesystems/sold#6]
Hello again. Now that the simple test is done, I've attempted to use sold in a much larger project to measure it against the standard linker.

First issue was another unknown command line option: `-executable_path`.

I don't really feel comfortable putting out entire detailed logs as the project is proprietary, but here is a portion of the command line emitted by the build (via clang++):

```
...
-Xlinker -no_deduplicate -stdlib\=libc++ -fobjc-link-runtime -fuse-ld\=sold -Xlinker -executable_path -Xlinker /Users/photex/workspaces/foo/PlatformSupport/Project/MacBuild/../../../../MacBag/arm64/Debug/LinkSupport/ExecutablePath -Xlinker -headerpad -Xlinker 800 -Xlinker -U -Xlinker _objc_readClassPair -F/System/Library/PrivateFrameworks/ -framework CoreSymbolication -framework Carbon -framework IOKit -framework System -lPlatformSupportAtomicAsm -Xlinker -no_adhoc_codesign
...
```

In order to use sold in our project, I'm setting `OTHER_LDFLAGS=-fuse-ld=sold` in our root xcconfig file. This is used by multiple projects in the workspace, but this error appears to occur in projects that are generating a framework rather than a dylib. I stopped the build before it got to any app bundles.

**Comment by rui314** [comment]
`-executable_path` is an undocumented option of ld64; you can't find that option in the man page. I don't know why the compiler passed that option, but I'll add support for the option.

**Comment by photex** [comment]
It might be pointless to guess, but I assumed it was setting the @executable_path similar to @rpath. 
I’ll try and replicate project setup with a minimal example instead.

**Comment by rui314** [comment]
Yes, it's a setting for the `@executable_path`. I implemented the feature and testing it now.

**Comment by rui314** [comment]
Please try again with the above change.

**Comment by rui314** [comment]
I'd also like to ask you that if you find that sold isn't fast enough, run it with `--perf` and copy-n-paste the output so that I can identify and improve slow passes.
