### ISSUE TITLE
Fishhook doesn't work with Sold

### ISSUE THREAD

**Issue by tapthaker** [bluewhalesystems/sold#7]
I am not sure if you'd be interested in fixing this, but it seems like Sold lays out the symbols referenced dynamically a bit differently than Ld64 or LLD, which causes the fishhook hack not to work. 

Here's a reproducer: https://github.com/tapthaker/sold-fishhook-reproducer

**Comment by tapthaker** [comment]
Another option could be to change the fishhook library such that it supports SOLD.

**Comment by rui314** [comment]
It looks like the lack of "indirect symbol table" makes Fishhook to be unable to find a dynamic symbol by name. I'm trying to add this section.

**Comment by rui314** [comment]
It should be fixed with the above change.
