### ISSUE TITLE
bad-relocation on x86_64 with Swift source code

### ISSUE THREAD

**Issue by tapthaker** [bluewhalesystems/sold#9]
I think this started happening recently, I didn't run into this error earlier. Here's a reproducer. I am also linking with `PPRiskMagnes` `FirebaseCoreInternal` which have failed in the past for me. 

[bad-relocation-repro.tar.gz](https://github.com/bluewhalesystems/sold/files/10494192/bad-relocation-repro.tar.gz)

**Comment by rui314** [comment]
Thanks, I believe it's fixed in the above patch.
